FROM dgoring/php:7.4-nginx

MAINTAINER David Goring

RUN sudo apt-get update \
 && sudo apt-get install -y --no-install-recommends \
    mariadb-server

# RUN sudo /usr/bin/mysql_secure_installation

COPY etc/supervisor.d/mysql.ini /etc/supervisor.d/
COPY etc/supervisor.d/create_database.ini /etc/supervisor.d/

COPY create_database.sh /
RUN sudo chmod o+x /create_database.sh

COPY run_override.sh /
RUN sudo chmod o+x /run_override.sh

EXPOSE 3306

ENTRYPOINT ["/run_override.sh"]
